global:
  scrape_interval: 15s  # frequência de coleta

scrape_configs:
  - job_name: 'firebird_exporter'
    static_configs:
      - targets: ['exporter:8000']  # nome do serviço do Docker e porta do Exporter
